jobs:
  include:
    - os: linux
      name: Android
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-29
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      before_install:
        - chmod +x ./deploy/android-prod.sh
        - openssl aes-256-cbc -K $encrypted_4f837f3546c7_key -iv $encrypted_4f837f3546c7_iv
          -in key.jks.enc -out key.jks -d
        - openssl aes-256-cbc -K $encrypted_a0c8cdfa8ab5_key -iv $encrypted_a0c8cdfa8ab5_iv
          -in pc-api-7545032973716901506-515-97970b2d55d2.json.enc -out pc-api-7545032973716901506-515-97970b2d55d2.json
          -d
        - yes | sdkmanager "platforms;android-29"
      install:
        - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
        - rvm install 2.6.0 && rvm use 2.6.0
        - git clone https://github.com/flutter/flutter.git -b stable
        - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - gem install bundler
        - cd android && bundle install && cd ..
      script:
        - flutter build appbundle --build-number $TRAVIS_BUILD_NUMBER
        - cd android
        - bundle exec fastlane deploy
