# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"  
  lane :deploy do
    upload_to_play_store(track: "internal", 
      aab: "../build/app/outputs/bundle/release/app-release.aab", 
      skip_upload_changelogs: true, 
      release_status: 'draft', 
    )
  end
  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    capture_android_screenshots(
      locales: ["en-US"],
      clear_previous_screenshots: true,
      app_apk_path: "../build/app/outputs/apk/debug/app-debug.apk",
    )
  end
end